/**
 * Extract ABIs from Hardhat artifacts and generate TypeScript exports
 *
 * This script walks through the artifacts directory, extracts ABIs from
 * contract JSON files, and generates TypeScript files that export them.
 *
 * Usage: tsx scripts/extract-abis.ts
 */

import * as fs from "fs";
import * as path from "path";

// Read from Hardhat's dist-hardhat output
const ARTIFACTS_DIR = path.join(
  __dirname,
  "..",
  "dist-hardhat",
  "artifacts",
  "contracts",
);
const OUTPUT_DIR = path.join(__dirname, "..", "src", "abis");

interface ArtifactJson {
  contractName: string;
  abi: unknown[];
  sourceName: string;
}

interface ExtractedAbi {
  contractName: string;
  abi: unknown[];
  sourcePath: string;
}

/**
 * Recursively find all artifact JSON files (excluding .dbg.json)
 */
function findArtifactFiles(dir: string): string[] {
  const files: string[] = [];

  if (!fs.existsSync(dir)) {
    console.error(`Artifacts directory not found: ${dir}`);
    console.error("Run 'hardhat compile' first to compile contracts.");
    process.exit(1);
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...findArtifactFiles(fullPath));
    } else if (
      entry.isFile() &&
      entry.name.endsWith(".json") &&
      !entry.name.endsWith(".dbg.json")
    ) {
      files.push(fullPath);
    }
  }

  return files;
}

/**
 * Extract ABI from an artifact file
 */
function extractAbi(filePath: string): ExtractedAbi | null {
  try {
    const content = fs.readFileSync(filePath, "utf-8");
    const artifact: ArtifactJson = JSON.parse(content);

    if (
      !artifact.abi ||
      !Array.isArray(artifact.abi) ||
      artifact.abi.length === 0
    ) {
      return null;
    }

    return {
      contractName: artifact.contractName,
      abi: artifact.abi,
      sourcePath: artifact.sourceName,
    };
  } catch (error) {
    console.warn(`Failed to parse ${filePath}:`, error);
    return null;
  }
}

/**
 * Generate TypeScript file content for an ABI
 */
function generateAbiFile(extracted: ExtractedAbi): string {
  const abiJson = JSON.stringify(extracted.abi, null, 2);

  return `/**
 * ABI for ${extracted.contractName}
 * Source: ${extracted.sourcePath}
 *
 * Auto-generated by extract-abis.ts - DO NOT EDIT
 */

export const ${extracted.contractName}Abi = ${abiJson} as const;

export type ${extracted.contractName}Abi = typeof ${extracted.contractName}Abi;
`;
}

/**
 * Generate barrel export file (index.ts)
 */
function generateIndexFile(contractNames: string[]): string {
  const exports = contractNames
    .map((name) => `export { ${name}Abi } from "./${name}";`)
    .join("\n");

  return `/**
 * Contract ABIs
 *
 * Auto-generated by extract-abis.ts - DO NOT EDIT
 */

${exports}
`;
}

/**
 * Main extraction logic
 */
function main() {
  console.log("🔍 Extracting ABIs from artifacts...\n");

  // Find all artifact files
  const artifactFiles = findArtifactFiles(ARTIFACTS_DIR);
  console.log(`Found ${artifactFiles.length} artifact files`);

  // Extract ABIs
  const extractedAbis: ExtractedAbi[] = [];
  for (const file of artifactFiles) {
    const extracted = extractAbi(file);
    if (extracted) {
      extractedAbis.push(extracted);
    }
  }

  console.log(`Extracted ${extractedAbis.length} ABIs\n`);

  // Filter to only include x402* contracts (the main protocol contracts)
  const mainContracts = extractedAbis.filter((e) => {
    // Only include contracts starting with "x402" (case-insensitive)
    return /^x402/i.test(e.contractName);
  });

  console.log(`Selected ${mainContracts.length} x402 contracts for export:`);
  mainContracts.forEach((c) => console.log(`  - ${c.contractName}`));
  console.log();

  // Create output directory
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    console.log(`Created directory: ${OUTPUT_DIR}`);
  }

  // Generate ABI files
  const generatedNames: string[] = [];
  for (const extracted of mainContracts) {
    const content = generateAbiFile(extracted);
    const fileName = `${extracted.contractName}.ts`;
    const filePath = path.join(OUTPUT_DIR, fileName);

    fs.writeFileSync(filePath, content);
    console.log(`✓ Generated ${fileName}`);
    generatedNames.push(extracted.contractName);
  }

  // Generate index file
  const indexContent = generateIndexFile(generatedNames);
  const indexPath = path.join(OUTPUT_DIR, "index.ts");
  fs.writeFileSync(indexPath, indexContent);
  console.log(`✓ Generated index.ts`);

  console.log(
    `\n✅ Successfully generated ${generatedNames.length} ABI files in ${OUTPUT_DIR}`,
  );
}

main();
