packages:
  - "clients/*"
  - "servers/*"
  - "fullstack/*"
  - "facilitator"
  - "legacy/facilitator"
  - "legacy/servers/*"
  - "legacy/clients/*"
  - "legacy/fullstack/*"
  - "legacy/dynamic_agent"
  - "legacy/agent"
  - "legacy/mcp-embedded-wallet"
  - "legacy/mpc"
  - "../../typescript/packages/core"
  - "../../typescript/packages/extensions"
  - "../../typescript/packages/http/*"
  - "../../typescript/packages/mechanisms/*"
  - "../../typescript/packages/legacy/*"
  - "../../typescript/packages/contracts/*"
